bytedance/bitsail

docs/connectors/introduction.md
docs/connectors/introduction_zh.md
docs/connectors/rocketmq/rocketmq-example.md
docs/connectors/rocketmq/rocketmq-example_zh.md
docs/connectors/rocketmq/rocketmq.md
docs/connectors/rocketmq/rocketmq_zh.md

Signed-off-by: Liu Peng <96pengpeng@gmail.com>
Add docs for rocketmq connector.
Add docs for rocketmq connector.
N/A
N/A

Add docs for rocketmq writer.

---

README.md

Change-Id: I9bb8a793d346af9abe5089a4eddf247bdbd0e9a7
Signed-off-by:
N/A

modify the introduction of bitsail

---

README.md

maybe hundreds of trillions of data is more often used，not hundreds of trillions data

revising typo

---

README.md
README_zh.md

Signed-off-by:
Remove connector duplicate declaration but not supported in Readme
Doris does not support reading and writing
N/A

[doc] Remove connector duplicate declaration but not supported in Readme

---

docs/connectors/introduction.md
docs/connectors/introduction_zh.md

Signed-off-by: Liu Peng <96pengpeng@gmail.com>
Add comment for streaming file connector.
N/A
N/A

add comment to StreamingFile

---

bitsail-connectors/bitsail-connectors-legacy/bitsail-connector-hudi/src/test/java/com/bytedance/bitsail/connector/legacy/hudi/sink/functional/ITTestDataStreamWrite.java

[MINOR] fix flaky hudi test

---

bitsail-components/bitsail-conversion-flink/bitsail-conversion-flink-hive/src/main/java/com/bytedance/bitsail/conversion/hive/BitSailColumnConversion.java
bitsail-components/bitsail-conversion-flink/bitsail-conversion-flink-hive/src/main/java/com/bytedance/bitsail/conversion/hive/HiveInspectors.java
bitsail-components/bitsail-conversion-flink/bitsail-conversion-flink-hive/src/test/java/com/bytedance/bitsail/conversion/hive/extractor/HiveWritableExtractorTest.java
bitsail-dist/pom.xml

[BitSail][Connector-Hive]Support tinyint type.

---

bitsail-connectors/connector-doris/src/main/java/com/bytedance/bitsail/connector/doris/error/DorisErrorCode.java
bitsail-connectors/connector-doris/src/main/java/com/bytedance/bitsail/connector/doris/partition/DorisPartitionHelper.java
bitsail-connectors/connector-doris/src/main/java/com/bytedance/bitsail/connector/doris/partition/DorisPartitionManager.java
bitsail-connectors/connector-doris/src/main/java/com/bytedance/bitsail/connector/doris/serialize/DorisRowSerializer.java

This PR just adds comments to some code and changes some code style.

---

docs/deployment.md
docs/deployment_zh.md

Signed-off-by:
Add jobmanager example (`localhost:8081`) example in local deployment document.
n/A
N/A

Add jm example in local deployment.

---

bitsail-connectors/bitsail-connectors-legacy/bitsail-connector-jdbc/src/main/java/com/bytedance/bitsail/connector/legacy/jdbc/constants/WriteModeProxy.java
bitsail-connectors/bitsail-connectors-legacy/bitsail-connector-jdbc/src/main/java/com/bytedance/bitsail/connector/legacy/jdbc/sink/JDBCOutputFormat.java
bitsail-connectors/bitsail-connectors-legacy/bitsail-connector-jdbc/src/main/java/com/bytedance/bitsail/connector/legacy/jdbc/utils/ignore/JDBCInsertIgnoreUtil.java
bitsail-connectors/bitsail-connectors-legacy/bitsail-connector-jdbc/src/main/java/com/bytedance/bitsail/connector/legacy/jdbc/utils/ignore/MysqlInsertIgnoreUtil.java
bitsail-connectors/bitsail-connectors-legacy/bitsail-connector-jdbc/src/test/java/com/bytedance/bitsail/connector/legacy/jdbc/ignore/MysqInsertIgnoreUtilTest.java

Signed-off-by:
https://github.com/bytedance/bitsail/issues/142
N/A

[BitSail][Connector] Support INSERT IGNORE INTO in mysql connector.

---

docs/connectors/Jdbc/jdbc.md
docs/connectors/Jdbc/jdbc_example.md
docs/connectors/Jdbc/jdbc_example_zh.md
docs/connectors/Jdbc/jdbc_zh.md

Signed-off-by:
add doc for #142 
N/A

[DOC]  DOC for INSERT IGNORE INTO in mysql connector

---

bitsail-common/src/main/java/com/bytedance/bitsail/common/configuration/BitSailConfiguration.java
bitsail-common/src/main/java/com/bytedance/bitsail/common/option/ConfigOption.java

Signed-off-by: Liu Peng
Support alias in config options.
Now options can have multiple keys by setting alias.
N/A
N/A

Support alias for options.

---

website/.vuepress/footer.ts

Signed-off-by:
Fix url failure.
Fix url failure.
N/A
N/A

[Bitsail][Docs]Update website.

---

bitsail-connectors/bitsail-connectors-legacy/bitsail-connector-hbase/src/main/java/com/bytedance/bitsail/connector/hbase/source/HBaseInputFormat.java
bitsail-connectors/bitsail-connectors-legacy/bitsail-connector-hbase/src/test/java/com/bytedance/bitsail/connector/hbase/sink/HBaseOutputFormatITCase.java
bitsail-connectors/bitsail-connectors-legacy/bitsail-connector-hbase/src/test/java/com/bytedance/bitsail/connector/hbase/source/HBaseInputFormatITCase.java
bitsail-connectors/bitsail-connectors-legacy/bitsail-connector-hbase/src/test/resources/hbase_to_print.json
bitsail-connectors/bitsail-connectors-legacy/bitsail-connector-hbase/src/test/resources/logback-test.xml
bitsail-test/bitsail-connector-test/pom.xml
bitsail-test/bitsail-connector-test/src/main/java/com/bytedance/bitsail/test/connector/test/testcontainers/hbase/HbaseCluster.java
bitsail-test/bitsail-connector-test/src/main/java/com/bytedance/bitsail/test/connector/test/testcontainers/hbase/HbaseContainer.java

Signed-off-by:
1.Add Hbase test container
2.Add unit test in hbase connector
3.fixed bug #226
4.fixed the `reuse Row` is null
#119 
N/A

[BitSail][Test] Add Hbase test container in bitsail-test

---

bitsail-connectors/bitsail-connectors-legacy/bitsail-connector-hudi/pom.xml

Compiled with jdk11.0.16 and maven 3.8.6

[BitSail] support compile with java11

---

bitsail-components/bitsail-component-formats-flink/bitsail-component-format-flink-api/src/main/java/com/bytedance/bitsail/component/format/api/RowBuilder.java
bitsail-components/bitsail-component-formats-flink/bitsail-component-format-flink-hive/src/main/java/com/bytedance/bitsail/component/format/hive/HiveGeneralRowBuilder.java
bitsail-components/bitsail-flink-row-parser/src/main/java/com/bytedance/bitsail/batch/parser/row/HiveRowBuilder.java
bitsail-components/bitsail-flink-row-parser/src/main/java/com/bytedance/bitsail/batch/parser/row/JsonRowBuilder.java
bitsail-components/bitsail-flink-row-parser/src/main/java/com/bytedance/bitsail/batch/parser/row/KVRowBuilder.java
bitsail-components/bitsail-flink-row-parser/src/main/java/com/bytedance/bitsail/batch/parser/row/TextRowBuilder.java
bitsail-connectors/bitsail-connectors-legacy/bitsail-connector-ftp/src/main/java/com/bytedance/bitsail/connector/legacy/ftp/source/FtpInputFormat.java
bitsail-connectors/bitsail-connectors-legacy/bitsail-connector-hadoop/src/main/java/com/bytedance/bitsail/connector/hadoop/source/HadoopInputFormat.java

Signed-off-by: Liu Peng
Support template in RowBuilder.
Support template in RowBuilder.
N/A
N/A

[BitSail][Connectors] Support template in RowBuilder.

---

website/en/community/contribute.md
website/zh/community/contribute.md

Signed-off-by: Liu Peng
Add guides for contributing documents. Especially telling developers how to test homepage locally.
Add guides for contributing documents. Especially telling developers how to test homepage locally.
N/A
N/A

[BitSail][Docs] Add guides for contributing documents.

---

bitsail-connectors/bitsail-connectors-legacy/bitsail-connector-hadoop/pom.xml
bitsail-connectors/bitsail-connectors-legacy/bitsail-connector-hadoop/src/test/java/com/bytedance/bitsail/connector/hadoop/source/HadoopInputFormatITCase.java
bitsail-connectors/bitsail-connectors-legacy/bitsail-connector-hadoop/src/test/resources/hadoop_to_print.json
bitsail-connectors/bitsail-connectors-legacy/bitsail-connector-hadoop/src/test/resources/source/test.json
bitsail-connectors/bitsail-connectors-legacy/bitsail-connector-hudi/pom.xml
bitsail-connectors/connector-druid/pom.xml
bitsail-test/bitsail-connector-test/pom.xml
bitsail-test/bitsail-connector-test/src/main/java/com/bytedance/bitsail/test/connector/test/minicluster/HdfsTestService.java
bitsail-test/bitsail-connector-test/src/main/java/com/bytedance/bitsail/test/connector/test/minicluster/MiniClusterUtil.java
bitsail-test/bitsail-connector-test/src/main/java/com/bytedance/bitsail/test/connector/test/minicluster/ZookeeperTestService.java
bitsail-test/bitsail-connector-test/src/main/java/com/bytedance/bitsail/test/connector/test/utils/FileIOUtils.java
bitsail-test/bitsail-connector-test/src/main/java/com/bytedance/bitsail/test/connector/test/utils/NetworkTestUtils.java
bitsail-test/bitsail-connector-test/src/main/java/com/bytedance/bitsail/test/connector/test/utils/Option.java

Signed-off-by:
- ✅ I have read through the [CONTRIBUTING.md](https://github.com/bytedance/bitsail/blob/master/docs/contributing.md) documentation.
- ✅ My code has the necessary comments and documentation (if needed).
- ✅ I have added relevant tests.
- Add Hadoop minicluster util in bitsail-test.
- Add HadoopInputFormatITCase using Hadoop minicluster util.
- Add Hadoop minicluster util in bitsail-test.
- Add HadoopInputFormatITCase using Hadoop minicluster util.
N/A

[BitSail][Test] Add Hadoop minicluster util in bitsail-test.

---

website/zh/blog/blog.md
website/zh/community/contribute.md
website/zh/documents/connectors/StreamingFile/StreamingFile.md
website/zh/documents/connectors/larksheet/larksheet.md

This PR fixes some documentation typos.

doc: Documentation typo fixes

---

website/en/documents/faq/README.md
website/zh/documents/faq/README.md

Signed-off-by:
We list faq document in bitsail website sidebar.

[BitSail][Doc] Show faq document in sidebar.

---

bitsail-connectors/connector-clickhouse/src/main/resources/clickhouse-type-converter.yaml
bitsail-connectors/connector-clickhouse/src/test/java/com/bytedance/bitsail/connector/clickhouse/ClickhouseContainerHolder.java
bitsail-connectors/connector-clickhouse/src/test/resources/clickhouse_to_print.json

Signed-off-by:
Support int128, int256 in ClickhouseSourceReader. They are converted to BigInteger.
_e.g._ Close #250 
N/A

[BitSail][Connector]Support int128, int256 in ClickhouseSourceReader

---

website/en/community/contribute.md
website/en/documents/start/README.md
website/en/documents/start/config.md
website/en/documents/start/deployment.md
website/en/documents/start/env_setup.md
website/zh/community/contribute.md
website/zh/documents/components/README.md
website/zh/documents/start/config.md
website/zh/documents/start/deployment.md
website/zh/documents/start/env_setup.md

Signed-off-by:
Fix the jump link between documents.
Just correct the relative path.
N/A
N/A

[BitSail][Docs] correct the jump link in documents.

---

bitsail-cores/bitsail-core-flink-base/src/main/java/com/bytedance/bitsail/flink/core/reader/PluginableInputFormatDAGBuilder.java

Signed-off-by: Liu Peng 
Current legacy connector may get null statistics, leading to NPE when computing parallelism.
Replace null statistics with empty statistics.
#268

Fix null statistics.

---

website/en/documents/connectors/jdbc/jdbc_example.md
website/zh/documents/connectors/jdbc/jdbc-example.md

Signed-off-by:
as title.
Close #290
N/A

[BitSail][Docs] fix code highlight

---

README.md
README_zh.md
bitsail-connectors/connector-assert/src/test/resources/assert_sink_col_check.json
bitsail-connectors/connector-assert/src/test/resources/assert_sink_row_check.json
website/en/documents/connectors/README.md
website/en/documents/connectors/assert/assert-example.md
website/en/documents/connectors/assert/assert.md
website/zh/documents/connectors/README.md
website/zh/documents/connectors/assert/assert-example.md
website/zh/documents/connectors/assert/assert.md

Signed-off-by:
Add Docs for Assert Sink Connector.
Close #300
N/A

[BitSail-300][Docs] Add Docs for Assert Sink Connector

---

bitsail-dist/pom.xml

Remove the duplicated dependency of logback.

[BitSail-296][Pom] Remove the duplicated dependency of logback

---

bitsail-connectors/bitsail-connectors-legacy/bitsail-connector-ftp/src/main/java/com/bytedance/bitsail/connector/legacy/ftp/client/IFtpHandler.java
bitsail-connectors/bitsail-connectors-legacy/bitsail-connector-ftp/src/main/java/com/bytedance/bitsail/connector/legacy/ftp/option/FtpReaderOptions.java
bitsail-connectors/bitsail-connectors-legacy/bitsail-connector-ftp/src/main/java/com/bytedance/bitsail/connector/legacy/ftp/source/FtpInputFormat.java
bitsail-connectors/bitsail-connectors-legacy/bitsail-connector-ftp/src/test/java/com/bytedance/bitsail/connector/legacy/ftp/client/FtpHandlerITCase.java
bitsail-connectors/bitsail-connectors-legacy/bitsail-connector-ftp/src/test/java/com/bytedance/bitsail/connector/legacy/ftp/source/FtpSourceITCase.java
bitsail-connectors/bitsail-connectors-legacy/bitsail-connector-ftp/src/test/java/com/bytedance/bitsail/connector/legacy/ftp/util/Constant.java
bitsail-connectors/bitsail-connectors-legacy/bitsail-connector-ftp/src/test/java/com/bytedance/bitsail/connector/legacy/ftp/util/SetupUtil.java
bitsail-connectors/bitsail-connectors-legacy/bitsail-connector-ftp/src/test/resources/scripts/ftp_to_print.json
website/en/documents/connectors/ftp/ftp.md
website/zh/documents/connectors/ftp/ftp.md

Signed-off-by:
Support more charset in FtpInputFormat
Support user defined charset by add config options
Close #252
N/A

[BitSail][Connector] Support more charset in FtpInputFormat

---

website/.vuepress/config.ts

[BitSail][Docs] Fix website favicon

---

build.sh
pom.xml

[BitSail] Bump version to 0.2.0-SNAPSHOT

---

.github/workflows/cicd.yml
tools/release/create_binary_tar.sh
tools/release/create_source_release.sh
tools/release/validate_source_release.sh

Add script to automate some release process

[BitSail] Add release util script

---

website/.vuepress/config.ts

[BitSail][Docs] Fix website favicon path prefix

---

LICENSE

LICENSE file should use copyright template instead of detailed copyright message.
Closed #239

[BitSail][LICENSE] Fix copyright template in LICENSE>

---

bitsail-connectors/connector-doris/src/test/java/com/bytedance/bitsail/connector/doris/converter/DorisRowConverterTest.java

Signed-off-by:
Add ut for DorisRowConverter
Construct a row, use the DorisRowConverter to convert each field and determine whether it is correct。
Close #256 
N/A

Add ut for DorisRowConverter

---

website/en/community/contribute.md
website/zh/community/contribute.md

Signed-off-by:
Close #355 
N/A

[BitSail[Doc] Optimize local deployment

---

website/.vuepress/footer.ts

Updated copyright #359

---

.github/workflows/cicd.yml

[BitSail] Add macos to cicd and disable windows UT

---

bitsail-common/src/main/java/com/bytedance/bitsail/common/option/CommonOptions.java
website/zh/documents/faq/README.md

Signed-off-by:
Current BitSailConfiguration only supports List and ArrayList as default class type.

Bugfix date formatter

---

bitsail-base/src/main/java/com/bytedance/bitsail/base/connector/reader/v1/Source.java
bitsail-base/src/main/java/com/bytedance/bitsail/base/connector/writer/v1/Sink.java
bitsail-base/src/main/java/com/bytedance/bitsail/base/serializer/BinarySerializer.java
bitsail-base/src/main/java/com/bytedance/bitsail/base/serializer/Serializer.java
bitsail-base/src/main/java/com/bytedance/bitsail/base/serializer/SimpleVersionedBinarySerializer.java
bitsail-base/src/main/java/com/bytedance/bitsail/base/serializer/VersionedSerializer.java
bitsail-base/src/test/java/com/bytedance/bitsail/base/serializer/SerializerTest.java
bitsail-connectors/connector-cdc/connector-cdc-base/src/main/java/com/bytedance/bitsail/connector/cdc/source/BinlogSource.java
bitsail-connectors/connector-doris/src/main/java/com/bytedance/bitsail/connector/doris/committer/DorisCommittableSerializer.java
bitsail-connectors/connector-doris/src/main/java/com/bytedance/bitsail/connector/doris/sink/DorisSink.java
bitsail-connectors/connector-selectdb/src/main/java/com/bytedance/bitsail/connector/selectdb/committer/SelectdbCommittableSerializer.java
bitsail-connectors/connector-selectdb/src/main/java/com/bytedance/bitsail/connector/selectdb/sink/SelectdbSink.java
bitsail-cores/bitsail-core-flink-base/src/main/java/com/bytedance/bitsail/flink/core/delagate/converter/FlinkRowConvertSerializer.java
bitsail-cores/bitsail-core-flink-bridge/src/main/java/com/bytedance/bitsail/core/flink/bridge/serializer/DelegateFlinkSourceSplitSerializer.java
bitsail-cores/bitsail-core-flink-bridge/src/main/java/com/bytedance/bitsail/core/flink/bridge/serializer/DelegateSimpleVersionedSerializer.java
bitsail-cores/bitsail-core-flink-bridge/src/test/java/com/bytedance/bitsail/core/flink/bridge/serializer/CommittableStateSerializerTest.java

[BitSail][Core] support version in serializer

---

bitsail-connectors/connector-cdc/connector-cdc-base/src/main/java/com/bytedance/bitsail/connector/cdc/error/BinlogReaderErrorCode.java
bitsail-connectors/connector-cdc/connector-cdc-base/src/main/java/com/bytedance/bitsail/connector/cdc/option/BinlogReaderOptions.java
bitsail-connectors/connector-cdc/connector-cdc-base/src/main/java/com/bytedance/bitsail/connector/cdc/source/BinlogSource.java
bitsail-connectors/connector-cdc/connector-cdc-base/src/main/java/com/bytedance/bitsail/connector/cdc/source/coordinator/CDCSourceSplitCoordinator.java
bitsail-connectors/connector-cdc/connector-cdc-base/src/main/java/com/bytedance/bitsail/connector/cdc/source/coordinator/state/AssignmentStateSerializer.java
bitsail-connectors/connector-cdc/connector-cdc-base/src/main/java/com/bytedance/bitsail/connector/cdc/source/coordinator/state/BaseAssignmentState.java
bitsail-connectors/connector-cdc/connector-cdc-base/src/main/java/com/bytedance/bitsail/connector/cdc/source/coordinator/state/BinlogAssignmentState.java
bitsail-connectors/connector-cdc/connector-cdc-base/src/main/java/com/bytedance/bitsail/connector/cdc/source/coordinator/state/SnapshotAssignmentState.java
bitsail-connectors/connector-cdc/connector-cdc-base/src/main/java/com/bytedance/bitsail/connector/cdc/source/coordinator/state/SplitType.java
bitsail-connectors/connector-cdc/connector-cdc-base/src/main/java/com/bytedance/bitsail/connector/cdc/source/offset/BinlogOffset.java
bitsail-connectors/connector-cdc/connector-cdc-base/src/main/java/com/bytedance/bitsail/connector/cdc/source/offset/BinlogOffsetType.java
bitsail-connectors/connector-cdc/connector-cdc-base/src/test/java/com/bytedance/bitsail/connector/cdc/source/coordinator/state/AssignmentStateSerializerTest.java
bitsail-connectors/connector-cdc/connector-cdc-base/src/test/java/com/bytedance/bitsail/connector/cdc/source/offset/BinlogOffsetTests.java
bitsail-connectors/connector-cdc/connector-cdc-mysql/src/main/java/com/bytedance/bitsail/connector/cdc/mysql/source/debezium/MysqlBinlogSplitReader.java
bitsail-connectors/connector-cdc/connector-cdc-mysql/src/test/java/com/bytedance/bitsail/connector/cdc/mysql/source/debezium/MysqlBinlogSplitReaderTest.java

[BitSail][Connector] cdc source state related improvement

---

README.md
README_zh.md
website/en/documents/connectors/README.md
website/en/documents/connectors/localfilesystem/localfilesystem-example.md
website/en/documents/connectors/localfilesystem/localfilesystem.md
website/zh/documents/connectors/README.md
website/zh/documents/connectors/localfilesystem/localfilesystem-example.md
website/zh/documents/connectors/localfilesystem/localfilesystem.md

Signed-off-by:
Update docs for LocalFileSystem connector.
N/A
N/A
N/A

[BitSail][Docs]: update docs for LocalFileSystem connector

---

bitsail-connectors/connector-cdc/connector-cdc-base/src/main/java/com/bytedance/bitsail/connector/cdc/error/BinlogReaderErrorCode.java
bitsail-connectors/connector-cdc/connector-cdc-base/src/main/java/com/bytedance/bitsail/connector/cdc/option/BinlogReaderOptions.java
bitsail-connectors/connector-cdc/connector-cdc-base/src/main/java/com/bytedance/bitsail/connector/cdc/source/coordinator/CDCSourceSplitCoordinator.java
bitsail-connectors/connector-cdc/connector-cdc-base/src/main/java/com/bytedance/bitsail/connector/cdc/source/offset/BinlogOffset.java
bitsail-connectors/connector-cdc/connector-cdc-base/src/main/java/com/bytedance/bitsail/connector/cdc/source/reader/BinlogSourceReader.java
bitsail-connectors/connector-cdc/connector-cdc-base/src/test/java/com/bytedance/bitsail/connector/cdc/source/offset/BinlogOffsetTests.java
bitsail-connectors/connector-cdc/connector-cdc-mysql/src/main/java/com/bytedance/bitsail/connector/cdc/mysql/source/config/MysqlConfig.java
bitsail-connectors/connector-cdc/connector-cdc-mysql/src/main/java/com/bytedance/bitsail/connector/cdc/mysql/source/constant/MysqlConstant.java
bitsail-connectors/connector-cdc/connector-cdc-mysql/src/main/java/com/bytedance/bitsail/connector/cdc/mysql/source/debezium/DebeziumHelper.java
bitsail-connectors/connector-cdc/connector-cdc-mysql/src/main/java/com/bytedance/bitsail/connector/cdc/mysql/source/debezium/MysqlBinlogSplitReader.java
bitsail-connectors/connector-cdc/connector-cdc-mysql/src/main/java/com/bytedance/bitsail/connector/cdc/mysql/source/reader/MysqlBinlogSourceReader.java
bitsail-connectors/connector-cdc/connector-cdc-mysql/src/test/java/com/bytedance/bitsail/connector/cdc/mysql/source/debezium/DebeziumHelperTest.java

[BitSail][Cdc] pass offset from jobConf to reader

---

bitsail-components/bitsail-component-formats/bitsail-component-format-json/src/main/java/com/bytedance/bitsail/component/format/json/RowToJsonConverter.java
bitsail-connectors/connector-kafka/pom.xml
bitsail-connectors/connector-kafka/src/main/java/com/bytedance/bitsail/connector/kafka/common/KafkaErrorCode.java
bitsail-connectors/connector-kafka/src/main/java/com/bytedance/bitsail/connector/kafka/constants/KafkaConstants.java
bitsail-connectors/connector-kafka/src/main/java/com/bytedance/bitsail/connector/kafka/model/KafkaRecord.java
bitsail-connectors/connector-kafka/src/main/java/com/bytedance/bitsail/connector/kafka/option/KafkaWriterOptions.java
bitsail-connectors/connector-kafka/src/main/java/com/bytedance/bitsail/connector/kafka/sink/KafkaProducer.java
bitsail-connectors/connector-kafka/src/main/java/com/bytedance/bitsail/connector/kafka/sink/KafkaSink.java
bitsail-connectors/connector-kafka/src/main/java/com/bytedance/bitsail/connector/kafka/sink/KafkaWriter.java
bitsail-connectors/connector-kafka/src/test/java/com/bytedance/bitsail/connector/kafka/sink/KafkaSinkITCase.java
bitsail-connectors/connector-kafka/src/test/resources/fake_to_kafka.json
bitsail-connectors/pom.xml
bitsail-dist/pom.xml

[BitSail][Connector] migrate kafka sink to v1 interface

---

bitsail-components/bitsail-component-formats/bitsail-component-format-json/src/main/java/com/bytedance/bitsail/component/format/json/JsonRowDeserializationSchema.java
bitsail-components/bitsail-component-formats/bitsail-component-format-json/src/main/java/com/bytedance/bitsail/component/format/json/JsonRowSerializationSchema.java
bitsail-components/bitsail-component-formats/bitsail-component-format-json/src/main/java/com/bytedance/bitsail/component/format/json/RowToJsonConverter.java
bitsail-components/bitsail-component-formats/bitsail-component-format-json/src/main/java/com/bytedance/bitsail/component/format/json/error/JsonFormatErrorCode.java
bitsail-components/bitsail-component-formats/bitsail-component-format-json/src/test/java/com/bytedance/bigsail/component/format/json/JsonRowDeserializationSchemaTest.java
bitsail-components/bitsail-component-formats/bitsail-component-format-json/src/test/java/com/bytedance/bigsail/component/format/json/JsonRowSerializationSchemaTest.java
bitsail-components/bitsail-component-formats/bitsail-component-format-json/src/test/java/com/bytedance/bigsail/component/format/json/RowToJsonConverterTest.java
bitsail-connectors/connector-ftp/src/main/java/com/bytedance/bitsail/connector/ftp/source/reader/DeserializationSchemaFactory.java
bitsail-connectors/connector-kafka/pom.xml
bitsail-connectors/connector-kafka/src/main/java/com/bytedance/bitsail/connector/kafka/option/KafkaWriterOptions.java
bitsail-connectors/connector-kafka/src/main/java/com/bytedance/bitsail/connector/kafka/sink/KafkaWriter.java
bitsail-connectors/connector-kafka/src/test/java/com/bytedance/bitsail/connector/kafka/sink/KafkaSinkITCase.java
bitsail-connectors/connector-localfilesystem/src/main/java/com/bytedance/bitsail/connector/localfilesystem/reader/DeserializationSchemaFactory.java
bitsail-connectors/connector-rocketmq/src/main/java/com/bytedance/bitsail/connector/rocketmq/format/RocketMQDeserializationSchema.java

[BitSail] support row to json converter in bitsail json format

---

website/en/documents/faq/README.md
website/zh/documents/faq/README.md

Signed-off-by:
Add more frequent questions into FAQs.
#266

[BitSail][Docs] Add more FAQs.

---

bitsail-connectors/connector-cdc/connector-cdc-base/src/main/java/com/bytedance/bitsail/connector/cdc/source/coordinator/CDCSourceSplitCoordinator.java
bitsail-connectors/connector-cdc/connector-cdc-base/src/main/java/com/bytedance/bitsail/connector/cdc/source/offset/BinlogOffset.java
bitsail-connectors/connector-cdc/connector-cdc-base/src/test/java/com/bytedance/bitsail/connector/cdc/source/coordinator/CDCSourceSplitCoordinatorTests.java
bitsail-connectors/connector-cdc/connector-cdc-mysql/src/test/java/com/bytedance/bitsail/connector/cdc/mysql/source/reader/MysqlBinlogSourceReaderTest.java

[BitSail][CDC] Add cdc source coordinator unit test

---

bitsail-connectors/connector-cdc/connector-cdc-base/src/main/java/com/bytedance/bitsail/connector/cdc/error/BinlogReaderErrorCode.java
bitsail-connectors/connector-cdc/connector-cdc-mysql/src/main/java/com/bytedance/bitsail/connector/cdc/mysql/source/debezium/DebeziumHelper.java
bitsail-connectors/connector-cdc/connector-cdc-mysql/src/main/java/com/bytedance/bitsail/connector/cdc/mysql/source/debezium/MysqlBinlogSplitReader.java
bitsail-connectors/connector-cdc/connector-cdc-mysql/src/test/java/com/bytedance/bitsail/connector/cdc/mysql/source/debezium/DebeziumHelperTest.java

[BitSail] Support get mysql latest offset

---

website/en/documents/start/deployment.md
website/zh/documents/start/deployment.md

Signed-off-by:
A follow-up change of K8S to update Deployment.md
A follow-up change of K8S to update Deployment.md
N/A
N/A

[BitSail][Features] K8S update Deployment.md section

---

bitsail-cores/bitsail-core-flink-base/src/main/java/com/bytedance/bitsail/flink/core/util/RowUtil.java

Support Timestamp type in RowUtil.
Change the import class from `java.secure.Timestamp` to `java.sql.Timestamp`.
- Fixes #433

[BitSail-433][Core] Support Timestamp type in RowUtil

---

bitsail-test/bitsail-test-end-to-end/bitsail-test-e2e-connector-v1/bitsail-test-e2e-connector-v1-redis/pom.xml
bitsail-test/bitsail-test-end-to-end/bitsail-test-e2e-connector-v1/pom.xml

- Title: [BitSail-449][Pom] Remove duplicate dependency of connector-redis
- Fixes: #449
Remove duplicate dependency of connector-redis.
*Describe the modifications you've done.*
**Please pick either of the following options.**
- Does this pull request introduce a new feature? (no)

[BitSail-449][Pom] Remove duplicate dependency of connector-redis

---

bitsail-cores/bitsail-core-flink/bitsail-core-flink-1.11-bridge/src/main/java/com/bytedance/bitsail/core/flink/bridge/writer/delegate/DelegateFlinkWriter.java

- Title: [BitSail-452][Core] Update Exception Information in DelegateFlinkWriter
- Fixes: #452 
>
>
>
as …

[BitSail-452][Core] Update Exception Information in DelegateFlinkWriter

---

bitsail-connectors/connector-cdc/connector-cdc-base/src/main/java/com/bytedance/bitsail/connector/cdc/error/BinlogReaderErrorCode.java
bitsail-connectors/connector-cdc/connector-cdc-mysql/pom.xml
bitsail-connectors/connector-cdc/connector-cdc-mysql/src/main/java/com/bytedance/bitsail/connector/cdc/mysql/source/debezium/DebeziumHelper.java
bitsail-connectors/connector-cdc/connector-cdc-mysql/src/main/java/com/bytedance/bitsail/connector/cdc/mysql/source/schema/MySqlSchemaFetcher.java
bitsail-connectors/connector-cdc/connector-cdc-mysql/src/main/java/com/bytedance/bitsail/connector/cdc/mysql/source/schema/SchemaUtils.java
bitsail-connectors/connector-cdc/connector-cdc-mysql/src/main/java/com/bytedance/bitsail/connector/cdc/mysql/source/sql/MysqlFieldDescriber.java
bitsail-connectors/connector-cdc/connector-cdc-mysql/src/main/java/com/bytedance/bitsail/connector/cdc/mysql/source/sql/MysqlTableDescriber.java
bitsail-connectors/connector-cdc/connector-cdc-mysql/src/test/java/com/bytedance/bitsail/connector/cdc/mysql/source/MockConnectionsTest.java
bitsail-connectors/connector-cdc/connector-cdc-mysql/src/test/java/com/bytedance/bitsail/connector/cdc/mysql/source/container/MySQLContainerMariadbAdapter.java
bitsail-connectors/connector-cdc/connector-cdc-mysql/src/test/java/com/bytedance/bitsail/connector/cdc/mysql/source/sql/MysqlFieldDescriberTest.java
bitsail-connectors/connector-cdc/connector-cdc-mysql/src/test/java/com/bytedance/bitsail/connector/cdc/mysql/source/sql/MysqlTableDescriberTest.java
bitsail-connectors/connector-cdc/connector-cdc-mysql/src/test/resources/logback-test.xml
bitsail-connectors/connector-cdc/connector-cdc-mysql/src/test/resources/scripts/insert_test.sql

- Title: [BitSail-XYZ][XxxType] Title of the pull request
- Fixes: #XYZ
>
>
>
*Describe the modifications …

[BitSail] support fetch schema from mysql

---

bitsail-connectors/connector-print/src/main/java/com/bytedance/bitsail/connector/print/sink/PrintWriter.java
bitsail-connectors/connector-print/src/main/java/com/bytedance/bitsail/connector/print/sink/PrintWriterCommitter.java
bitsail-connectors/connector-print/src/main/java/com/bytedance/bitsail/connector/print/sink/option/PrintWriterOptions.java
bitsail-test/bitsail-test-end-to-end/bitsail-test-e2e-connector-v1/bitsail-test-e2e-connector-v1-clickhouse/src/test/resources/clickhouse_to_print.json
bitsail-test/bitsail-test-end-to-end/bitsail-test-e2e-connector-v1/bitsail-test-e2e-connector-v1-ftp/src/test/resources/sftp_to_print.json
bitsail-test/bitsail-test-end-to-end/bitsail-test-e2e-connector-v1/bitsail-test-e2e-connector-v1-print/src/test/resources/fake_to_print.json
bitsail-test/bitsail-test-integration/bitsail-test-integration-larksheet/src/test/resources/larksheet_to_print.json
website/en/community/contribute.md
website/en/documents/connectors/README.md
website/en/documents/connectors/print/print-example.md
website/en/documents/connectors/print/print.md
website/en/documents/connectors/print/v1/print-example-v1.md
website/en/documents/connectors/print/v1/print-v1.md
website/en/documents/introduce.md
website/zh/community/contribute.md
website/zh/documents/connectors/README.md
website/zh/documents/connectors/print/print.md
website/zh/documents/connectors/print/v1/print-v1-example.md
website/zh/documents/connectors/print/v1/print-v1.md
website/zh/documents/introduce.md

- Title: [BitSail-454][Connector] Remove unused option in print connector
- Fixes: #454
>
>
>
- Remove …

[BitSail-454][Connector] Remove unused option in print connector

---

bitsail-connectors/connector-cdc/connector-cdc-base/src/main/java/com/bytedance/bitsail/connector/cdc/source/BaseCDCSource.java
bitsail-connectors/connector-cdc/connector-cdc-base/src/main/java/com/bytedance/bitsail/connector/cdc/source/coordinator/CDCSourceSplitCoordinator.java
bitsail-connectors/connector-cdc/connector-cdc-base/src/main/java/com/bytedance/bitsail/connector/cdc/source/reader/BaseCDCSourceReader.java
bitsail-connectors/connector-cdc/connector-cdc-base/src/main/java/com/bytedance/bitsail/connector/cdc/source/split/BinlogSplit.java
bitsail-connectors/connector-cdc/connector-cdc-mysql/src/main/java/com/bytedance/bitsail/connector/cdc/mysql/source/MysqlCDCSource.java
bitsail-connectors/connector-cdc/connector-cdc-mysql/src/main/java/com/bytedance/bitsail/connector/cdc/mysql/source/debezium/InMemoryDatabaseHistory.java
bitsail-connectors/connector-cdc/connector-cdc-mysql/src/main/java/com/bytedance/bitsail/connector/cdc/mysql/source/debezium/MysqlBinlogSplitReader.java
bitsail-connectors/connector-cdc/connector-cdc-mysql/src/main/java/com/bytedance/bitsail/connector/cdc/mysql/source/reader/MysqlCDCSourceReader.java
bitsail-connectors/connector-cdc/connector-cdc-mysql/src/test/java/com/bytedance/bitsail/connector/cdc/mysql/source/MockConnectionsTest.java

- Title: [BitSail-XYZ][XxxType] Title of the pull request
- Fixes: #XYZ
>
>
>
*Describe the modifications …

[BitSail] mysql cdc support batch mode

---

bitsail-common/src/test/java/com/bytedance/bitsail/common/typeinfo/TypeInfoCompatiblesColumnCompareTest.java

- Title: [BitSail-488][UT] Fixed TypeInfoCompatiblesColumnCompareTest not pass 
- Fixes: #488
>
>
> …

[BitSail-488][UT] Fixed TypeInfoCompatiblesColumnCompareTest not pass 

---

website/zh/documents/start/deployment.md

- Title: [BitSail-XYZ][XxxType] Title of the pull request
- Fixes: #XYZ
>
>
>
*Describe the modifications …

Fixed ch deployment.md 文档修复 修复 k8s启动Application文档错误问题
